config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("patlove.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("",include("patlove.portal.urls"),name="portal"),
    path("adopt/",include("patlove.rescuePet.urls"),name="rescuepet")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

patlove/portal/urls.py
from django.urls import path
from .views import Home
urlpatterns = [
    path("",Home.as_view(),name="home")
]

patlove/portal/models.py
from django.db import models

class Banner(models.Model):
    title = models.CharField("Title banner",help_text="Add a title for show in banner", max_length=30)
    short_description = models.CharField("Short Description",help_text = "Add a short description for banner",max_length = 100)
    background_img = models.ImageField("Image background",help_text="Add a image for the background in banner",upload_to="banner")
    button_message = models.CharField("Button message",help_text = "Add a call to action message",max_length = 13,blank=True,null=True)
    
    def __str__(self) -> str:
        return self.title

class ServiceInfo(models.Model):
    title = models.CharField("Title service section",help_text="Title for section services")
    description = models.TextField("Description services section",help_text = "Description services section")
    image = models.ImageField("Image for services section",upload_to="service-section")
    
class Service(models.Model):
    title = models.CharField("Title service",help_text="Title for services")
    description = models.TextField("Description services ",help_text = "Description services ")
    icon = models.CharField("Select Icon",help_text="Select icon for services",max_length=100)
    serviceInfo = models.ForeignKey(
    ServiceInfo,
    on_delete=models.CASCADE,
    related_name="services"
  )
    

patlove/rescuePet/models.py
from django.db import models
from django.core.validators import MinValueValidator


SPECIES_CHOICES = [
    ("DG","DOG"),
    ("CT","CAT")
]

GENDER_CHOICES = [
    ('M','Male'),
    ('F','Female')
]

SIZE_CHOICES = [
    ('B','Big'),
    ('M','Medium'),
    ('S','Small')
]

AGE_CHOICES=[
    ("A","Adult"),
    ("K","Kitten"),
    ("Y","Young"),
    ("S","Senior")
]

class RescuePet(models.Model):
    name = models.CharField("Name of Rescue Pet",max_length=100)
    species = models.CharField("Specie of rescue pet",max_length = 4,choices=SPECIES_CHOICES)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    age = models.CharField("Age of rescue pet",choices=AGE_CHOICES,max_length=1)
    neutered = models.BooleanField("It's neutered?",default=False)
    vaccinated = models.BooleanField("It's vaccinated",default = False)
    size = models.CharField("Size rescue pet",choices=SIZE_CHOICES,max_length=1 )
    about = models.TextField("About rescue pet")
    amount_adoption_fee = models.CharField("Amount adoption fee",blank=True,null=True,default="0")
    adopted = models.BooleanField("Adopted pet",default =False)
    
    def __str__(self) -> str:
        return self.name

class RescuePetPhoto(models.Model):
    image=models.ImageField(upload_to="rescuePet")
    rescuePet = models.ForeignKey(RescuePet,on_delete=models.CASCADE,related_name = "rescuePetPhoto")
    

patlove/portal/views.py
from typing import Any
from django.views.generic import TemplateView

class Home(TemplateView):
    template_name = "index.html"
    

patlove/portal/templates/pages/adoption_list.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="jumbotron jumbotron-fluid overlay">
    {% comment %} <div class="jumbo-heading">
      <!-- section-heading -->
      <div class="section-heading" data-aos="zoom-in">
        <h1>Adoption</h1>
      </div>
      <!-- /section-heading -->
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">Home</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Adoption</li>
        </ol>
      </nav>
    </div>
    <!-- /jumbo-heading --> {% endcomment %}
  </div>
  <!-- ==== Page Content ==== -->
  <div class="page">
    <div class="container block-padding pt-0">
      <div class="col-lg-8 offset-lg-2 text-center">
        <h3>Find a new furry Friend</h3>
        <p>Aliquam erat lorem ipsum volutpat In id fermentum augue, ut pellentesque leo. Maecenas at arcu risus. Donec commodo sodales ex, scelerisque laoreet nibh hendrerit id. In aliquet magna nec lobortis maximus. Etiam rhoncus leo a dolor placerat, nec elementum ipsum convall.</p>
      </div>
      {% if rows < 4 %}
        <div class="row mt-5">
          {% for pet in pets_rows %}
            <!-- Pet -->
            <div class="adopt-card col-md-6 col-xl-3 res-margin">
              <div class="card bg-light-custom">
                <div class="thumbnail text-center">
                  <!-- Image -->
                  {% with pet.rescuePetPhoto.first as photo %}
                    <img src="{{ photo.image.url }}" class="border-irregular1 img-fluid" alt="" />
                  {% endwith %}
                  <!-- Name -->
                  <div class="caption-adoption">
                    <h6 class="adoption-header">{{ pet.name }}</h6>
                    <!-- List -->
                    <ul class="list-unstyled">
                      <li>
                        <strong>Gender:</strong> {{ pet.get_gender_display }}
                      </li>
                      <li>
                        <strong>Neutered:</strong> {% if pet.neutered %}
                          Yes
                        {% else %}
                          No
                        {% endif %}
                      </li>
                      <li>
                        <strong>Age:</strong> {{ pet.get_age_display }}
                      </li>
                    </ul>
                    <!-- Buttons -->
                    <div class="text-center">
                      <a href="{{ pet.id }}" class="btn btn-primary">More Info</a>
                    </div>
                  </div>
                </div>
                <!-- /thumbnail -->
              </div>
              <!-- /card -->
            </div>
            <!-- /adopt-card -->
          {% endfor %}
        </div>
      {% else %}
        {% for row in pets_rows %}
          <div class="row mt-5">
            {% for pet in row %}
              <!-- Pet -->
              <div class="adopt-card col-md-6 col-xl-3 res-margin">
                <div class="card bg-light-custom">
                  <div class="thumbnail text-center">
                    <!-- Image -->
                    {% with pet.rescuePetPhoto.first as photos %}
                      <img src="{{ photos.image.url }}" class="border-irregular1 img-fluid" alt="" />
                    {% endwith %}
                    <!-- Name -->
                    <div class="caption-adoption">
                      <h6 class="adoption-header">{{ pet.name }}</h6>
                      <!-- List -->
                      <ul class="list-unstyled">
                        <li>
                          <strong>Gender:</strong> {{ pet.get_gender_display }}
                        </li>
                        <li>
                          <strong>Neutered:</strong> {% if pet.neutered %}
                            Yes
                          {% else %}
                            No
                          {% endif %}
                        </li>
                        <li>
                          <strong>Age:</strong> {{ pet.get_age_display }}
                        </li>
                      </ul>
                      <!-- Buttons -->
                      <div class="text-center">
                        <a href="{% url 'detail_pet' pet.id %}" class="btn btn-primary">More Info</a>
                      </div>
                    </div>
                  </div>
                  <!-- /thumbnail -->
                </div>
                <!-- /card -->
              </div>
              <!-- /adopt-card -->
            {% endfor %}
          </div>
        {% endfor %}
      {% endif %}

      <div class="col-md-12 mt-5">
        <!-- pagination -->
        <nav aria-label="pagination">
          <ul class="pagination float-right">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}">Previus</a>
              </li>
            {% endif %}
            {% for page in page_obj.paginator.page_range %}
            <li class="page-item">
              <a class="page-link {% if page == page_obj.number %} active{% endif %}" href="?page={{page}}">{{page}}</a>
            </li>
            {% endfor %}
            
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
              </li>
            {% endif %}
          </ul>
        </nav>
        <!-- /nav -->
      </div>
      <!-- /col-md -->
    </div>
    <!-- /container -->
  </div>
  <!-- /page -->
{% endblock %}

patlove/portal/templates/pages/detail_pet.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="page">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row bg-light-custom border-irregular1 block-padding">
            <!-- image -->
            <div class="col-lg-4 offset-lg-2">
              <!-- owl slider -->
              <div id="owl-adopt-single" class="owl-carousel top-centered-nav owl-theme">
               {% if pet.rescuePetPhoto.all|length > 1%}
               {% for photo in pet.rescuePetPhoto.all %}
                <div class="col-md-12">
                  <!-- image -->
                  <a href="{{ photo.image.url }}" title="{{pet.name}}"><img src="{{ photo.image.url }}" class="border-irregular1 img-fluid hover-opacity" alt="" /></a>
                </div>
                <!-- /col-md-12 -->
                {% endfor %}
                {% else %}
                <div class="col-md-12">
                  <!-- image -->
                  <a href="{{ pet.rescuePetPhoto.first.image.url }}" title="{{pet.name}}"><img src="{{ pet.rescuePetPhoto.first.image.url }}" class="border-irregular1 img-fluid hover-opacity" alt="" /></a>
                </div>
                <!-- /col-md-12 -->
                {% endif %}
               
              </div>
              <!-- /owl-carousel -->
            </div>
            <!-- /col-md -->
            <!-- adoption info -->
            <div class="col-lg-4 res-margin mt-5 text-xs-center">
              <h4><strong>Pet name:</strong> {{pet.name}}</h4>
              <div class="row">
                <div class="col-sm-6">
                  <ul class="list-unstyled pet-adopt-info">
                    <li class="h7">
                      Gender: <span>{{pet.get_gender_display|capfirst}}</span>
                    </li>
                    <li class="h7">
                      Age: <span>{{pet.get_age_display|capfirst}} </span>
                    </li>
                    <li class="h7">
                      Size: <span>{{pet.get_size_display|capfirst}}</span>
                    </li>
                  </ul>
                </div>
                <div class="col-sm-6">
                  <ul class="list-unstyled pet-adopt-info">
                    <li class="h7">
                      Neutered: <span>{{pet.neutered}}</span>
                    </li>
                    <li class="h7">
                      Vaccinated: <span>{{pet.vaccinated}}</span>
                    </li>
                    
                  </ul>
                </div>
                <!-- /div -->
              </div>
              <!-- /row -->
              {% comment %} <p class="font-weight-bold">Fluffy is a very sweet and active dog, she is ready for a new home!</p> {% endcomment %}
              <!-- button -->
              <a href="#" class="btn btn-primary" data-aos="zoom-in">Adopt now!</a>
            </div>
            <!-- /col-md -->
          </div>
          <!-- /row -->
          <div class="col-md-12 mt-5">
            <h3>About {{pet.name}}</h3>
            <!-- ul custom -->
            {% comment %} <ul class="custom list-inline font-weight-bold">
              <li class="list-inline-item">Friendly to other dogs</li>
              <li class="list-inline-item">Good for Apartments</li>
              <li class="list-inline-item">Friendly with Kids</li>
            </ul> {% endcomment %}
            <p>{{pet.about}}</p>
            <div class="alert alert-primary mt-5" role="alert">
              <h6 class="text-light">Adoption Rules</h6>
              <p>Elit uasi quidem minus id omnis a nibh fusce mollis imperdie tlorem ipuset phas ellus ac sodales Lorem ipsum dolor Phas ellus ac sodales felis tiam non metus. lorem ipsum dolor sit amet, consectetur adipisicing elit uasi quidem minus id omnis a nibh fusce mollis imperdie tlorem ipuset campas fincas</p>
            </div>
            <!-- /alert -->
            <p class="custom-link">
              <a href="adoption.html">« Go back to adoption gallery</a>
            </p>
          </div>
          <!-- /col-md -->
        </div>
        <!-- /col-lg -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
{% endblock %}